version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tinvest
      POSTGRES_PASSWORD: tinvest_password
      POSTGRES_DB: tinvest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    depends_on:
      - db
volumes:
  postgres_data: