// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "tinvest/internal/service/trading_strategy/rsi_pullback/live/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Announce provides a mock function with no fields
func (_m *MockService) Announce() {
	_m.Called()
}

// MockService_Announce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Announce'
type MockService_Announce_Call struct {
	*mock.Call
}

// Announce is a helper method to define mock.On call
func (_e *MockService_Expecter) Announce() *MockService_Announce_Call {
	return &MockService_Announce_Call{Call: _e.mock.On("Announce")}
}

func (_c *MockService_Announce_Call) Run(run func()) *MockService_Announce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Announce_Call) Return() *MockService_Announce_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_Announce_Call) RunAndReturn(run func()) *MockService_Announce_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function with given fields: ctx, in
func (_m *MockService) Run(ctx context.Context, in dto.Run) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Run) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockService_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - in dto.Run
func (_e *MockService_Expecter) Run(ctx interface{}, in interface{}) *MockService_Run_Call {
	return &MockService_Run_Call{Call: _e.mock.On("Run", ctx, in)}
}

func (_c *MockService_Run_Call) Run(run func(ctx context.Context, in dto.Run)) *MockService_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.Run))
	})
	return _c
}

func (_c *MockService_Run_Call) Return(_a0 error) *MockService_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Run_Call) RunAndReturn(run func(context.Context, dto.Run) error) *MockService_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
