// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "tinvest/pkg/client/grpc/model"

	time "time"
)

// MockoperationsClient is an autogenerated mock type for the operationsClient type
type MockoperationsClient struct {
	mock.Mock
}

type MockoperationsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockoperationsClient) EXPECT() *MockoperationsClient_Expecter {
	return &MockoperationsClient_Expecter{mock: &_m.Mock}
}

// GetAvailableCash provides a mock function with given fields: ctx, accountID
func (_m *MockoperationsClient) GetAvailableCash(ctx context.Context, accountID string) (float64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableCash")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockoperationsClient_GetAvailableCash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableCash'
type MockoperationsClient_GetAvailableCash_Call struct {
	*mock.Call
}

// GetAvailableCash is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockoperationsClient_Expecter) GetAvailableCash(ctx interface{}, accountID interface{}) *MockoperationsClient_GetAvailableCash_Call {
	return &MockoperationsClient_GetAvailableCash_Call{Call: _e.mock.On("GetAvailableCash", ctx, accountID)}
}

func (_c *MockoperationsClient_GetAvailableCash_Call) Run(run func(ctx context.Context, accountID string)) *MockoperationsClient_GetAvailableCash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockoperationsClient_GetAvailableCash_Call) Return(_a0 float64, _a1 error) *MockoperationsClient_GetAvailableCash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockoperationsClient_GetAvailableCash_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MockoperationsClient_GetAvailableCash_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrumentTrades provides a mock function with given fields: ctx, accountID, instrumentID, from, to
func (_m *MockoperationsClient) GetInstrumentTrades(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time) ([]model.Trade, error) {
	ret := _m.Called(ctx, accountID, instrumentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentTrades")
	}

	var r0 []model.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)); ok {
		return rf(ctx, accountID, instrumentID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []model.Trade); ok {
		r0 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockoperationsClient_GetInstrumentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentTrades'
type MockoperationsClient_GetInstrumentTrades_Call struct {
	*mock.Call
}

// GetInstrumentTrades is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - instrumentID string
//   - from time.Time
//   - to time.Time
func (_e *MockoperationsClient_Expecter) GetInstrumentTrades(ctx interface{}, accountID interface{}, instrumentID interface{}, from interface{}, to interface{}) *MockoperationsClient_GetInstrumentTrades_Call {
	return &MockoperationsClient_GetInstrumentTrades_Call{Call: _e.mock.On("GetInstrumentTrades", ctx, accountID, instrumentID, from, to)}
}

func (_c *MockoperationsClient_GetInstrumentTrades_Call) Run(run func(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time)) *MockoperationsClient_GetInstrumentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockoperationsClient_GetInstrumentTrades_Call) Return(_a0 []model.Trade, _a1 error) *MockoperationsClient_GetInstrumentTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockoperationsClient_GetInstrumentTrades_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)) *MockoperationsClient_GetInstrumentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolio provides a mock function with given fields: ctx, accountID
func (_m *MockoperationsClient) GetPortfolio(ctx context.Context, accountID string) ([]*model.Position, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Position, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Position); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockoperationsClient_GetPortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolio'
type MockoperationsClient_GetPortfolio_Call struct {
	*mock.Call
}

// GetPortfolio is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockoperationsClient_Expecter) GetPortfolio(ctx interface{}, accountID interface{}) *MockoperationsClient_GetPortfolio_Call {
	return &MockoperationsClient_GetPortfolio_Call{Call: _e.mock.On("GetPortfolio", ctx, accountID)}
}

func (_c *MockoperationsClient_GetPortfolio_Call) Run(run func(ctx context.Context, accountID string)) *MockoperationsClient_GetPortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockoperationsClient_GetPortfolio_Call) Return(_a0 []*model.Position, _a1 error) *MockoperationsClient_GetPortfolio_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockoperationsClient_GetPortfolio_Call) RunAndReturn(run func(context.Context, string) ([]*model.Position, error)) *MockoperationsClient_GetPortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolioTotal provides a mock function with given fields: ctx, accountID
func (_m *MockoperationsClient) GetPortfolioTotal(ctx context.Context, accountID string) (float64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolioTotal")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockoperationsClient_GetPortfolioTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolioTotal'
type MockoperationsClient_GetPortfolioTotal_Call struct {
	*mock.Call
}

// GetPortfolioTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockoperationsClient_Expecter) GetPortfolioTotal(ctx interface{}, accountID interface{}) *MockoperationsClient_GetPortfolioTotal_Call {
	return &MockoperationsClient_GetPortfolioTotal_Call{Call: _e.mock.On("GetPortfolioTotal", ctx, accountID)}
}

func (_c *MockoperationsClient_GetPortfolioTotal_Call) Run(run func(ctx context.Context, accountID string)) *MockoperationsClient_GetPortfolioTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockoperationsClient_GetPortfolioTotal_Call) Return(_a0 float64, _a1 error) *MockoperationsClient_GetPortfolioTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockoperationsClient_GetPortfolioTotal_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MockoperationsClient_GetPortfolioTotal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockoperationsClient creates a new instance of MockoperationsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockoperationsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockoperationsClient {
	mock := &MockoperationsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
