// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "tinvest/pkg/client/grpc/model"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockTradesClient is an autogenerated mock type for the TradesClient type
type MockTradesClient struct {
	mock.Mock
}

type MockTradesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTradesClient) EXPECT() *MockTradesClient_Expecter {
	return &MockTradesClient_Expecter{mock: &_m.Mock}
}

// GetInstrumentTrades provides a mock function with given fields: ctx, accountID, instrumentID, from, to
func (_m *MockTradesClient) GetInstrumentTrades(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time) ([]model.Trade, error) {
	ret := _m.Called(ctx, accountID, instrumentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentTrades")
	}

	var r0 []model.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)); ok {
		return rf(ctx, accountID, instrumentID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []model.Trade); ok {
		r0 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTradesClient_GetInstrumentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentTrades'
type MockTradesClient_GetInstrumentTrades_Call struct {
	*mock.Call
}

// GetInstrumentTrades is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - instrumentID string
//   - from time.Time
//   - to time.Time
func (_e *MockTradesClient_Expecter) GetInstrumentTrades(ctx interface{}, accountID interface{}, instrumentID interface{}, from interface{}, to interface{}) *MockTradesClient_GetInstrumentTrades_Call {
	return &MockTradesClient_GetInstrumentTrades_Call{Call: _e.mock.On("GetInstrumentTrades", ctx, accountID, instrumentID, from, to)}
}

func (_c *MockTradesClient_GetInstrumentTrades_Call) Run(run func(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time)) *MockTradesClient_GetInstrumentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockTradesClient_GetInstrumentTrades_Call) Return(_a0 []model.Trade, _a1 error) *MockTradesClient_GetInstrumentTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTradesClient_GetInstrumentTrades_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)) *MockTradesClient_GetInstrumentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTradesClient creates a new instance of MockTradesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTradesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTradesClient {
	mock := &MockTradesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
