// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	model "tinvest/internal/service/trading_strategy/scalping/model"
	strategy "tinvest/internal/service/trading_strategy/scalping/strategy"

	mock "github.com/stretchr/testify/mock"
)

// MockStrategy is an autogenerated mock type for the Strategy type
type MockStrategy struct {
	mock.Mock
}

type MockStrategy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStrategy) EXPECT() *MockStrategy_Expecter {
	return &MockStrategy_Expecter{mock: &_m.Mock}
}

// Decide provides a mock function with given fields: md
func (_m *MockStrategy) Decide(md strategy.MarketData) model.Signal {
	ret := _m.Called(md)

	if len(ret) == 0 {
		panic("no return value specified for Decide")
	}

	var r0 model.Signal
	if rf, ok := ret.Get(0).(func(strategy.MarketData) model.Signal); ok {
		r0 = rf(md)
	} else {
		r0 = ret.Get(0).(model.Signal)
	}

	return r0
}

// MockStrategy_Decide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decide'
type MockStrategy_Decide_Call struct {
	*mock.Call
}

// Decide is a helper method to define mock.On call
//   - md strategy.MarketData
func (_e *MockStrategy_Expecter) Decide(md interface{}) *MockStrategy_Decide_Call {
	return &MockStrategy_Decide_Call{Call: _e.mock.On("Decide", md)}
}

func (_c *MockStrategy_Decide_Call) Run(run func(md strategy.MarketData)) *MockStrategy_Decide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(strategy.MarketData))
	})
	return _c
}

func (_c *MockStrategy_Decide_Call) Return(_a0 model.Signal) *MockStrategy_Decide_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrategy_Decide_Call) RunAndReturn(run func(strategy.MarketData) model.Signal) *MockStrategy_Decide_Call {
	_c.Call.Return(run)
	return _c
}

// Lookback provides a mock function with no fields
func (_m *MockStrategy) Lookback() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lookback")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockStrategy_Lookback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lookback'
type MockStrategy_Lookback_Call struct {
	*mock.Call
}

// Lookback is a helper method to define mock.On call
func (_e *MockStrategy_Expecter) Lookback() *MockStrategy_Lookback_Call {
	return &MockStrategy_Lookback_Call{Call: _e.mock.On("Lookback")}
}

func (_c *MockStrategy_Lookback_Call) Run(run func()) *MockStrategy_Lookback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStrategy_Lookback_Call) Return(_a0 int) *MockStrategy_Lookback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrategy_Lookback_Call) RunAndReturn(run func() int) *MockStrategy_Lookback_Call {
	_c.Call.Return(run)
	return _c
}

// Ticker provides a mock function with no fields
func (_m *MockStrategy) Ticker() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ticker")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStrategy_Ticker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ticker'
type MockStrategy_Ticker_Call struct {
	*mock.Call
}

// Ticker is a helper method to define mock.On call
func (_e *MockStrategy_Expecter) Ticker() *MockStrategy_Ticker_Call {
	return &MockStrategy_Ticker_Call{Call: _e.mock.On("Ticker")}
}

func (_c *MockStrategy_Ticker_Call) Run(run func()) *MockStrategy_Ticker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStrategy_Ticker_Call) Return(_a0 string) *MockStrategy_Ticker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStrategy_Ticker_Call) RunAndReturn(run func() string) *MockStrategy_Ticker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStrategy creates a new instance of MockStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStrategy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStrategy {
	mock := &MockStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
