// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	investapi "tinvest/internal/pb/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockOrdersClient is an autogenerated mock type for the OrdersClient type
type MockOrdersClient struct {
	mock.Mock
}

type MockOrdersClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrdersClient) EXPECT() *MockOrdersClient_Expecter {
	return &MockOrdersClient_Expecter{mock: &_m.Mock}
}

// PostOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrdersClient) PostOrder(ctx context.Context, in *investapi.PostOrderRequest, opts ...grpc.CallOption) (*investapi.PostOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostOrder")
	}

	var r0 *investapi.PostOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.PostOrderRequest, ...grpc.CallOption) (*investapi.PostOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.PostOrderRequest, ...grpc.CallOption) *investapi.PostOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investapi.PostOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *investapi.PostOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrdersClient_PostOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostOrder'
type MockOrdersClient_PostOrder_Call struct {
	*mock.Call
}

// PostOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *investapi.PostOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrdersClient_Expecter) PostOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrdersClient_PostOrder_Call {
	return &MockOrdersClient_PostOrder_Call{Call: _e.mock.On("PostOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrdersClient_PostOrder_Call) Run(run func(ctx context.Context, in *investapi.PostOrderRequest, opts ...grpc.CallOption)) *MockOrdersClient_PostOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*investapi.PostOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrdersClient_PostOrder_Call) Return(_a0 *investapi.PostOrderResponse, _a1 error) *MockOrdersClient_PostOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrdersClient_PostOrder_Call) RunAndReturn(run func(context.Context, *investapi.PostOrderRequest, ...grpc.CallOption) (*investapi.PostOrderResponse, error)) *MockOrdersClient_PostOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrdersClient creates a new instance of MockOrdersClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrdersClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrdersClient {
	mock := &MockOrdersClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
