// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: msg
func (_m *MockClient) SendMessage(msg string) error {
	ret := _m.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockClient_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - msg string
func (_e *MockClient_Expecter) SendMessage(msg interface{}) *MockClient_SendMessage_Call {
	return &MockClient_SendMessage_Call{Call: _e.mock.On("SendMessage", msg)}
}

func (_c *MockClient_SendMessage_Call) Run(run func(msg string)) *MockClient_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_SendMessage_Call) Return(_a0 error) *MockClient_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SendMessage_Call) RunAndReturn(run func(string) error) *MockClient_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageToChat provides a mock function with given fields: chatID, msg
func (_m *MockClient) SendMessageToChat(chatID int64, msg string) error {
	ret := _m.Called(chatID, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageToChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string) error); ok {
		r0 = rf(chatID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SendMessageToChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageToChat'
type MockClient_SendMessageToChat_Call struct {
	*mock.Call
}

// SendMessageToChat is a helper method to define mock.On call
//   - chatID int64
//   - msg string
func (_e *MockClient_Expecter) SendMessageToChat(chatID interface{}, msg interface{}) *MockClient_SendMessageToChat_Call {
	return &MockClient_SendMessageToChat_Call{Call: _e.mock.On("SendMessageToChat", chatID, msg)}
}

func (_c *MockClient_SendMessageToChat_Call) Run(run func(chatID int64, msg string)) *MockClient_SendMessageToChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockClient_SendMessageToChat_Call) Return(_a0 error) *MockClient_SendMessageToChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SendMessageToChat_Call) RunAndReturn(run func(int64, string) error) *MockClient_SendMessageToChat_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessageToTopic provides a mock function with given fields: chatID, threadID, msg
func (_m *MockClient) SendMessageToTopic(chatID int64, threadID int, msg string) error {
	ret := _m.Called(chatID, threadID, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessageToTopic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int, string) error); ok {
		r0 = rf(chatID, threadID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_SendMessageToTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageToTopic'
type MockClient_SendMessageToTopic_Call struct {
	*mock.Call
}

// SendMessageToTopic is a helper method to define mock.On call
//   - chatID int64
//   - threadID int
//   - msg string
func (_e *MockClient_Expecter) SendMessageToTopic(chatID interface{}, threadID interface{}, msg interface{}) *MockClient_SendMessageToTopic_Call {
	return &MockClient_SendMessageToTopic_Call{Call: _e.mock.On("SendMessageToTopic", chatID, threadID, msg)}
}

func (_c *MockClient_SendMessageToTopic_Call) Run(run func(chatID int64, threadID int, msg string)) *MockClient_SendMessageToTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockClient_SendMessageToTopic_Call) Return(_a0 error) *MockClient_SendMessageToTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_SendMessageToTopic_Call) RunAndReturn(run func(int64, int, string) error) *MockClient_SendMessageToTopic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
