// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "tinvest/pkg/client/grpc/model"
)

// MockUsersServiceClient is an autogenerated mock type for the UsersServiceClient type
type MockUsersServiceClient struct {
	mock.Mock
}

type MockUsersServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsersServiceClient) EXPECT() *MockUsersServiceClient_Expecter {
	return &MockUsersServiceClient_Expecter{mock: &_m.Mock}
}

// GetAccounts provides a mock function with given fields: ctx
func (_m *MockUsersServiceClient) GetAccounts(ctx context.Context) ([]model.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUsersServiceClient_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type MockUsersServiceClient_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUsersServiceClient_Expecter) GetAccounts(ctx interface{}) *MockUsersServiceClient_GetAccounts_Call {
	return &MockUsersServiceClient_GetAccounts_Call{Call: _e.mock.On("GetAccounts", ctx)}
}

func (_c *MockUsersServiceClient_GetAccounts_Call) Run(run func(ctx context.Context)) *MockUsersServiceClient_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUsersServiceClient_GetAccounts_Call) Return(_a0 []model.Account, _a1 error) *MockUsersServiceClient_GetAccounts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUsersServiceClient_GetAccounts_Call) RunAndReturn(run func(context.Context) ([]model.Account, error)) *MockUsersServiceClient_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsersServiceClient creates a new instance of MockUsersServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsersServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsersServiceClient {
	mock := &MockUsersServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
