// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "tinvest/pkg/client/grpc/model"

	time "time"
)

// MockOperationsServiceClient is an autogenerated mock type for the OperationsServiceClient type
type MockOperationsServiceClient struct {
	mock.Mock
}

type MockOperationsServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationsServiceClient) EXPECT() *MockOperationsServiceClient_Expecter {
	return &MockOperationsServiceClient_Expecter{mock: &_m.Mock}
}

// GetAvailableCash provides a mock function with given fields: ctx, accountID
func (_m *MockOperationsServiceClient) GetAvailableCash(ctx context.Context, accountID string) (float64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableCash")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetAvailableCash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailableCash'
type MockOperationsServiceClient_GetAvailableCash_Call struct {
	*mock.Call
}

// GetAvailableCash is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockOperationsServiceClient_Expecter) GetAvailableCash(ctx interface{}, accountID interface{}) *MockOperationsServiceClient_GetAvailableCash_Call {
	return &MockOperationsServiceClient_GetAvailableCash_Call{Call: _e.mock.On("GetAvailableCash", ctx, accountID)}
}

func (_c *MockOperationsServiceClient_GetAvailableCash_Call) Run(run func(ctx context.Context, accountID string)) *MockOperationsServiceClient_GetAvailableCash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetAvailableCash_Call) Return(_a0 float64, _a1 error) *MockOperationsServiceClient_GetAvailableCash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetAvailableCash_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MockOperationsServiceClient_GetAvailableCash_Call {
	_c.Call.Return(run)
	return _c
}

// GetCashOperations provides a mock function with given fields: ctx, accountID, from, to
func (_m *MockOperationsServiceClient) GetCashOperations(ctx context.Context, accountID string, from time.Time, to time.Time) ([]model.CashOperation, error) {
	ret := _m.Called(ctx, accountID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetCashOperations")
	}

	var r0 []model.CashOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) ([]model.CashOperation, error)); ok {
		return rf(ctx, accountID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, time.Time) []model.CashOperation); ok {
		r0 = rf(ctx, accountID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CashOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, accountID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetCashOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCashOperations'
type MockOperationsServiceClient_GetCashOperations_Call struct {
	*mock.Call
}

// GetCashOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - from time.Time
//   - to time.Time
func (_e *MockOperationsServiceClient_Expecter) GetCashOperations(ctx interface{}, accountID interface{}, from interface{}, to interface{}) *MockOperationsServiceClient_GetCashOperations_Call {
	return &MockOperationsServiceClient_GetCashOperations_Call{Call: _e.mock.On("GetCashOperations", ctx, accountID, from, to)}
}

func (_c *MockOperationsServiceClient_GetCashOperations_Call) Run(run func(ctx context.Context, accountID string, from time.Time, to time.Time)) *MockOperationsServiceClient_GetCashOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetCashOperations_Call) Return(_a0 []model.CashOperation, _a1 error) *MockOperationsServiceClient_GetCashOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetCashOperations_Call) RunAndReturn(run func(context.Context, string, time.Time, time.Time) ([]model.CashOperation, error)) *MockOperationsServiceClient_GetCashOperations_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstrumentTrades provides a mock function with given fields: ctx, accountID, instrumentID, from, to
func (_m *MockOperationsServiceClient) GetInstrumentTrades(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time) ([]model.Trade, error) {
	ret := _m.Called(ctx, accountID, instrumentID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetInstrumentTrades")
	}

	var r0 []model.Trade
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)); ok {
		return rf(ctx, accountID, instrumentID, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time, time.Time) []model.Trade); ok {
		r0 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Trade)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time, time.Time) error); ok {
		r1 = rf(ctx, accountID, instrumentID, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetInstrumentTrades_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstrumentTrades'
type MockOperationsServiceClient_GetInstrumentTrades_Call struct {
	*mock.Call
}

// GetInstrumentTrades is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - instrumentID string
//   - from time.Time
//   - to time.Time
func (_e *MockOperationsServiceClient_Expecter) GetInstrumentTrades(ctx interface{}, accountID interface{}, instrumentID interface{}, from interface{}, to interface{}) *MockOperationsServiceClient_GetInstrumentTrades_Call {
	return &MockOperationsServiceClient_GetInstrumentTrades_Call{Call: _e.mock.On("GetInstrumentTrades", ctx, accountID, instrumentID, from, to)}
}

func (_c *MockOperationsServiceClient_GetInstrumentTrades_Call) Run(run func(ctx context.Context, accountID string, instrumentID string, from time.Time, to time.Time)) *MockOperationsServiceClient_GetInstrumentTrades_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Time), args[4].(time.Time))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetInstrumentTrades_Call) Return(_a0 []model.Trade, _a1 error) *MockOperationsServiceClient_GetInstrumentTrades_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetInstrumentTrades_Call) RunAndReturn(run func(context.Context, string, string, time.Time, time.Time) ([]model.Trade, error)) *MockOperationsServiceClient_GetInstrumentTrades_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperation provides a mock function with given fields: ctx, accountID, figi
func (_m *MockOperationsServiceClient) GetOperation(ctx context.Context, accountID string, figi string) ([]*model.Operation, error) {
	ret := _m.Called(ctx, accountID, figi)

	if len(ret) == 0 {
		panic("no return value specified for GetOperation")
	}

	var r0 []*model.Operation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*model.Operation, error)); ok {
		return rf(ctx, accountID, figi)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*model.Operation); ok {
		r0 = rf(ctx, accountID, figi)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Operation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, accountID, figi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperation'
type MockOperationsServiceClient_GetOperation_Call struct {
	*mock.Call
}

// GetOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
//   - figi string
func (_e *MockOperationsServiceClient_Expecter) GetOperation(ctx interface{}, accountID interface{}, figi interface{}) *MockOperationsServiceClient_GetOperation_Call {
	return &MockOperationsServiceClient_GetOperation_Call{Call: _e.mock.On("GetOperation", ctx, accountID, figi)}
}

func (_c *MockOperationsServiceClient_GetOperation_Call) Run(run func(ctx context.Context, accountID string, figi string)) *MockOperationsServiceClient_GetOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetOperation_Call) Return(_a0 []*model.Operation, _a1 error) *MockOperationsServiceClient_GetOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetOperation_Call) RunAndReturn(run func(context.Context, string, string) ([]*model.Operation, error)) *MockOperationsServiceClient_GetOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolio provides a mock function with given fields: ctx, accountID
func (_m *MockOperationsServiceClient) GetPortfolio(ctx context.Context, accountID string) ([]*model.Position, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolio")
	}

	var r0 []*model.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.Position, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.Position); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Position)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetPortfolio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolio'
type MockOperationsServiceClient_GetPortfolio_Call struct {
	*mock.Call
}

// GetPortfolio is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockOperationsServiceClient_Expecter) GetPortfolio(ctx interface{}, accountID interface{}) *MockOperationsServiceClient_GetPortfolio_Call {
	return &MockOperationsServiceClient_GetPortfolio_Call{Call: _e.mock.On("GetPortfolio", ctx, accountID)}
}

func (_c *MockOperationsServiceClient_GetPortfolio_Call) Run(run func(ctx context.Context, accountID string)) *MockOperationsServiceClient_GetPortfolio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetPortfolio_Call) Return(_a0 []*model.Position, _a1 error) *MockOperationsServiceClient_GetPortfolio_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetPortfolio_Call) RunAndReturn(run func(context.Context, string) ([]*model.Position, error)) *MockOperationsServiceClient_GetPortfolio_Call {
	_c.Call.Return(run)
	return _c
}

// GetPortfolioTotal provides a mock function with given fields: ctx, accountID
func (_m *MockOperationsServiceClient) GetPortfolioTotal(ctx context.Context, accountID string) (float64, error) {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for GetPortfolioTotal")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, accountID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOperationsServiceClient_GetPortfolioTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPortfolioTotal'
type MockOperationsServiceClient_GetPortfolioTotal_Call struct {
	*mock.Call
}

// GetPortfolioTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID string
func (_e *MockOperationsServiceClient_Expecter) GetPortfolioTotal(ctx interface{}, accountID interface{}) *MockOperationsServiceClient_GetPortfolioTotal_Call {
	return &MockOperationsServiceClient_GetPortfolioTotal_Call{Call: _e.mock.On("GetPortfolioTotal", ctx, accountID)}
}

func (_c *MockOperationsServiceClient_GetPortfolioTotal_Call) Run(run func(ctx context.Context, accountID string)) *MockOperationsServiceClient_GetPortfolioTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOperationsServiceClient_GetPortfolioTotal_Call) Return(_a0 float64, _a1 error) *MockOperationsServiceClient_GetPortfolioTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOperationsServiceClient_GetPortfolioTotal_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MockOperationsServiceClient_GetPortfolioTotal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOperationsServiceClient creates a new instance of MockOperationsServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationsServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationsServiceClient {
	mock := &MockOperationsServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
