// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	investapi "tinvest/internal/pb/v1"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CancelStopOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) CancelStopOrder(ctx context.Context, in *investapi.CancelStopOrderRequest, opts ...grpc.CallOption) (*investapi.CancelStopOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelStopOrder")
	}

	var r0 *investapi.CancelStopOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.CancelStopOrderRequest, ...grpc.CallOption) (*investapi.CancelStopOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.CancelStopOrderRequest, ...grpc.CallOption) *investapi.CancelStopOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investapi.CancelStopOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *investapi.CancelStopOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CancelStopOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelStopOrder'
type MockClient_CancelStopOrder_Call struct {
	*mock.Call
}

// CancelStopOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *investapi.CancelStopOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) CancelStopOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_CancelStopOrder_Call {
	return &MockClient_CancelStopOrder_Call{Call: _e.mock.On("CancelStopOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_CancelStopOrder_Call) Run(run func(ctx context.Context, in *investapi.CancelStopOrderRequest, opts ...grpc.CallOption)) *MockClient_CancelStopOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*investapi.CancelStopOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_CancelStopOrder_Call) Return(_a0 *investapi.CancelStopOrderResponse, _a1 error) *MockClient_CancelStopOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CancelStopOrder_Call) RunAndReturn(run func(context.Context, *investapi.CancelStopOrderRequest, ...grpc.CallOption) (*investapi.CancelStopOrderResponse, error)) *MockClient_CancelStopOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetStopOrders provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) GetStopOrders(ctx context.Context, in *investapi.GetStopOrdersRequest, opts ...grpc.CallOption) (*investapi.GetStopOrdersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetStopOrders")
	}

	var r0 *investapi.GetStopOrdersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.GetStopOrdersRequest, ...grpc.CallOption) (*investapi.GetStopOrdersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.GetStopOrdersRequest, ...grpc.CallOption) *investapi.GetStopOrdersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investapi.GetStopOrdersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *investapi.GetStopOrdersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetStopOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStopOrders'
type MockClient_GetStopOrders_Call struct {
	*mock.Call
}

// GetStopOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - in *investapi.GetStopOrdersRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) GetStopOrders(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_GetStopOrders_Call {
	return &MockClient_GetStopOrders_Call{Call: _e.mock.On("GetStopOrders",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_GetStopOrders_Call) Run(run func(ctx context.Context, in *investapi.GetStopOrdersRequest, opts ...grpc.CallOption)) *MockClient_GetStopOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*investapi.GetStopOrdersRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_GetStopOrders_Call) Return(_a0 *investapi.GetStopOrdersResponse, _a1 error) *MockClient_GetStopOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetStopOrders_Call) RunAndReturn(run func(context.Context, *investapi.GetStopOrdersRequest, ...grpc.CallOption) (*investapi.GetStopOrdersResponse, error)) *MockClient_GetStopOrders_Call {
	_c.Call.Return(run)
	return _c
}

// PostStopOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockClient) PostStopOrder(ctx context.Context, in *investapi.PostStopOrderRequest, opts ...grpc.CallOption) (*investapi.PostStopOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostStopOrder")
	}

	var r0 *investapi.PostStopOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.PostStopOrderRequest, ...grpc.CallOption) (*investapi.PostStopOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *investapi.PostStopOrderRequest, ...grpc.CallOption) *investapi.PostStopOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*investapi.PostStopOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *investapi.PostStopOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_PostStopOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostStopOrder'
type MockClient_PostStopOrder_Call struct {
	*mock.Call
}

// PostStopOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *investapi.PostStopOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockClient_Expecter) PostStopOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockClient_PostStopOrder_Call {
	return &MockClient_PostStopOrder_Call{Call: _e.mock.On("PostStopOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockClient_PostStopOrder_Call) Run(run func(ctx context.Context, in *investapi.PostStopOrderRequest, opts ...grpc.CallOption)) *MockClient_PostStopOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*investapi.PostStopOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_PostStopOrder_Call) Return(_a0 *investapi.PostStopOrderResponse, _a1 error) *MockClient_PostStopOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_PostStopOrder_Call) RunAndReturn(run func(context.Context, *investapi.PostStopOrderRequest, ...grpc.CallOption) (*investapi.PostStopOrderResponse, error)) *MockClient_PostStopOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
