package golden_x

import (
	"errors"
	"math"
	"testing"
	"time"

	"tinvest/internal/model"
	"tinvest/internal/service/trading_strategy/golden_x/dto"
)

func TestComputeEMA(t *testing.T) {
	// Period=3 EMA over the sequence [1,2,3,4,5,6]:
	// seed (pos 2) = (1+2+3)/3 = 2
	// multiplier  = 2/(3+1) = 0.5
	// pos 3: (4-2)*0.5 + 2 = 3
	// pos 4: (5-3)*0.5 + 3 = 4
	// pos 5: (6-4)*0.5 + 4 = 5
	got := computeEMA([]float64{1, 2, 3, 4, 5, 6}, 3)
	want := []float64{0, 0, 2, 3, 4, 5}
	if len(got) != len(want) {
		t.Fatalf("len = %d, want %d", len(got), len(want))
	}
	for i := range want {
		if math.Abs(got[i]-want[i]) > 1e-9 {
			t.Errorf("pos %d: got %v, want %v", i, got[i], want[i])
		}
	}
}

func TestComputeEMA_InsufficientReturnsZeroes(t *testing.T) {
	got := computeEMA([]float64{1, 2}, 3)
	if len(got) != 2 {
		t.Fatalf("len = %d, want 2", len(got))
	}
	for i, v := range got {
		if v != 0 {
			t.Errorf("pos %d: got %v, want 0", i, v)
		}
	}
}

// candleAt builds a CandleItemTechAnalyse with Time t and Close c (Units only).
func candleAt(t time.Time, c int64) *model.CandleItemTechAnalyse {
	return &model.CandleItemTechAnalyse{
		Time:  t,
		Close: model.Quotation{Units: c},
	}
}

func TestTrendStatusFromCandles(t *testing.T) {
	msk := mustLoad(t, "Europe/Moscow")
	// "now" = Thursday 2026-05-14 12:00 MSK
	// Current week opens Mon 2026-05-11 00:00.
	now := time.Date(2026, 5, 14, 12, 0, 0, 0, msk)
	currentWeekOpen := time.Date(2026, 5, 11, 0, 0, 0, 0, msk)

	// Helper to build N consecutive weekly candles ending on `last` with closes
	// generated by `closeFn(i)`. i=0 is the oldest, i=N-1 is the newest.
	build := func(last time.Time, n int, closeFn func(i int) int64) []*model.CandleItemTechAnalyse {
		out := make([]*model.CandleItemTechAnalyse, n)
		for i := 0; i < n; i++ {
			weekTime := last.AddDate(0, 0, -7*(n-1-i))
			out[i] = candleAt(weekTime, closeFn(i))
		}
		return out
	}

	lastClosedWeek := time.Date(2026, 5, 4, 0, 0, 0, 0, msk)

	t.Run("rising series — close above EMA → dto.TrendWith", func(t *testing.T) {
		// 10 weeks, period=3, strictly increasing closes: last close >> EMA.
		candles := build(lastClosedWeek, 10, func(i int) int64 { return int64(100 + i*5) })
		got, err := trendStatusFromCandles(candles, 3, now, msk)
		if err != nil {
			t.Fatalf("unexpected err: %v", err)
		}
		if got != dto.TrendWith {
			t.Fatalf("got %v, want dto.TrendWith", got)
		}
	})

	t.Run("falling series — close below EMA → dto.TrendAgainst", func(t *testing.T) {
		candles := build(lastClosedWeek, 10, func(i int) int64 { return int64(200 - i*5) })
		got, err := trendStatusFromCandles(candles, 3, now, msk)
		if err != nil {
			t.Fatalf("unexpected err: %v", err)
		}
		if got != dto.TrendAgainst {
			t.Fatalf("got %v, want dto.TrendAgainst", got)
		}
	})

	t.Run("close == EMA → dto.TrendAgainst (strict >)", func(t *testing.T) {
		// All-same closes: EMA == close everywhere. Strict comparison means
		// equality is treated as "against trend" — see the plan.
		candles := build(lastClosedWeek, 10, func(int) int64 { return 100 })
		got, err := trendStatusFromCandles(candles, 3, now, msk)
		if err != nil {
			t.Fatalf("unexpected err: %v", err)
		}
		if got != dto.TrendAgainst {
			t.Fatalf("got %v, want dto.TrendAgainst", got)
		}
	})

	t.Run("insufficient history — fewer closed weeks than period", func(t *testing.T) {
		candles := build(lastClosedWeek, 2, func(i int) int64 { return int64(100 + i) })
		_, err := trendStatusFromCandles(candles, 3, now, msk)
		if !errors.Is(err, ErrInsufficientHistory) {
			t.Fatalf("err = %v, want ErrInsufficientHistory", err)
		}
	})

	t.Run("current open week is discarded from history count", func(t *testing.T) {
		// 3 candles total: 2 closed + 1 on the current open week.
		// period=3 → not enough closed candles → ErrInsufficientHistory.
		candles := []*model.CandleItemTechAnalyse{
			candleAt(lastClosedWeek.AddDate(0, 0, -7), 100),
			candleAt(lastClosedWeek, 110),
			candleAt(currentWeekOpen, 999),
		}
		_, err := trendStatusFromCandles(candles, 3, now, msk)
		if !errors.Is(err, ErrInsufficientHistory) {
			t.Fatalf("err = %v, want ErrInsufficientHistory", err)
		}
	})

	t.Run("current open week does not bias the comparison", func(t *testing.T) {
		// 4 closed candles at 100 + 1 current-week candle with huge close.
		// Period=3 → status must be based on closed candles only (equal → dto.TrendAgainst).
		candles := []*model.CandleItemTechAnalyse{
			candleAt(lastClosedWeek.AddDate(0, 0, -21), 100),
			candleAt(lastClosedWeek.AddDate(0, 0, -14), 100),
			candleAt(lastClosedWeek.AddDate(0, 0, -7), 100),
			candleAt(lastClosedWeek, 100),
			candleAt(currentWeekOpen, 10_000),
		}
		got, err := trendStatusFromCandles(candles, 3, now, msk)
		if err != nil {
			t.Fatalf("unexpected err: %v", err)
		}
		if got != dto.TrendAgainst {
			t.Fatalf("got %v, want dto.TrendAgainst", got)
		}
	})
}

func TestTrendStatus_Mark(t *testing.T) {
	tests := []struct {
		status dto.TrendStatus
		want   string
	}{
		{dto.TrendWith, "✅"},
		{dto.TrendAgainst, "🚫"},
		{dto.TrendUnknown, ""},
	}
	for _, tc := range tests {
		if got := tc.status.Mark(); got != tc.want {
			t.Errorf("status %v: got %q, want %q", tc.status, got, tc.want)
		}
	}
}
