// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "tinvest/internal/model"

	mock "github.com/stretchr/testify/mock"

	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// MockcandleFetcher is an autogenerated mock type for the candleFetcher type
type MockcandleFetcher struct {
	mock.Mock
}

type MockcandleFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcandleFetcher) EXPECT() *MockcandleFetcher_Expecter {
	return &MockcandleFetcher_Expecter{mock: &_m.Mock}
}

// GetCandles provides a mock function with given fields: ctx, instrumentUID, interval, from, to, limit, withHoliday
func (_m *MockcandleFetcher) GetCandles(ctx context.Context, instrumentUID *string, interval int32, from *timestamppb.Timestamp, to *timestamppb.Timestamp, limit *int32, withHoliday bool) ([]*model.CandleItemTechAnalyse, error) {
	ret := _m.Called(ctx, instrumentUID, interval, from, to, limit, withHoliday)

	if len(ret) == 0 {
		panic("no return value specified for GetCandles")
	}

	var r0 []*model.CandleItemTechAnalyse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string, int32, *timestamppb.Timestamp, *timestamppb.Timestamp, *int32, bool) ([]*model.CandleItemTechAnalyse, error)); ok {
		return rf(ctx, instrumentUID, interval, from, to, limit, withHoliday)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string, int32, *timestamppb.Timestamp, *timestamppb.Timestamp, *int32, bool) []*model.CandleItemTechAnalyse); ok {
		r0 = rf(ctx, instrumentUID, interval, from, to, limit, withHoliday)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CandleItemTechAnalyse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string, int32, *timestamppb.Timestamp, *timestamppb.Timestamp, *int32, bool) error); ok {
		r1 = rf(ctx, instrumentUID, interval, from, to, limit, withHoliday)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockcandleFetcher_GetCandles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCandles'
type MockcandleFetcher_GetCandles_Call struct {
	*mock.Call
}

// GetCandles is a helper method to define mock.On call
//   - ctx context.Context
//   - instrumentUID *string
//   - interval int32
//   - from *timestamppb.Timestamp
//   - to *timestamppb.Timestamp
//   - limit *int32
//   - withHoliday bool
func (_e *MockcandleFetcher_Expecter) GetCandles(ctx interface{}, instrumentUID interface{}, interval interface{}, from interface{}, to interface{}, limit interface{}, withHoliday interface{}) *MockcandleFetcher_GetCandles_Call {
	return &MockcandleFetcher_GetCandles_Call{Call: _e.mock.On("GetCandles", ctx, instrumentUID, interval, from, to, limit, withHoliday)}
}

func (_c *MockcandleFetcher_GetCandles_Call) Run(run func(ctx context.Context, instrumentUID *string, interval int32, from *timestamppb.Timestamp, to *timestamppb.Timestamp, limit *int32, withHoliday bool)) *MockcandleFetcher_GetCandles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string), args[2].(int32), args[3].(*timestamppb.Timestamp), args[4].(*timestamppb.Timestamp), args[5].(*int32), args[6].(bool))
	})
	return _c
}

func (_c *MockcandleFetcher_GetCandles_Call) Return(_a0 []*model.CandleItemTechAnalyse, _a1 error) *MockcandleFetcher_GetCandles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockcandleFetcher_GetCandles_Call) RunAndReturn(run func(context.Context, *string, int32, *timestamppb.Timestamp, *timestamppb.Timestamp, *int32, bool) ([]*model.CandleItemTechAnalyse, error)) *MockcandleFetcher_GetCandles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcandleFetcher creates a new instance of MockcandleFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcandleFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcandleFetcher {
	mock := &MockcandleFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
