// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "tinvest/internal/model"
)

// MockinstrumentsClient is an autogenerated mock type for the instrumentsClient type
type MockinstrumentsClient struct {
	mock.Mock
}

type MockinstrumentsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockinstrumentsClient) EXPECT() *MockinstrumentsClient_Expecter {
	return &MockinstrumentsClient_Expecter{mock: &_m.Mock}
}

// Shares provides a mock function with given fields: ctx
func (_m *MockinstrumentsClient) Shares(ctx context.Context) ([]*model.Share, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shares")
	}

	var r0 []*model.Share
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*model.Share, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Share); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Share)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockinstrumentsClient_Shares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shares'
type MockinstrumentsClient_Shares_Call struct {
	*mock.Call
}

// Shares is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockinstrumentsClient_Expecter) Shares(ctx interface{}) *MockinstrumentsClient_Shares_Call {
	return &MockinstrumentsClient_Shares_Call{Call: _e.mock.On("Shares", ctx)}
}

func (_c *MockinstrumentsClient_Shares_Call) Run(run func(ctx context.Context)) *MockinstrumentsClient_Shares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockinstrumentsClient_Shares_Call) Return(_a0 []*model.Share, _a1 error) *MockinstrumentsClient_Shares_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockinstrumentsClient_Shares_Call) RunAndReturn(run func(context.Context) ([]*model.Share, error)) *MockinstrumentsClient_Shares_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockinstrumentsClient creates a new instance of MockinstrumentsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockinstrumentsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockinstrumentsClient {
	mock := &MockinstrumentsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
